'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { apiUrl } from '@/lib/api-url';
type Post = { name: string; role: string; time: string; text: string; image?: string; video?: string };
export default function PostDetailClient({ id }: { id: string }) {
  const [post, setPost] = useState<Post | null>(null); const [comments, setComments] = useState<string[]>([]); const [comment, setComment] = useState('');
  useEffect(() => { fetch(apiUrl(`/api/posts/${id}`)).then(r => r.ok ? r.json() : Promise.reject()).then(d => setPost(d.post)).catch(() => setPost(null)); fetch(apiUrl(`/api/posts/${id}/comments`)).then(r => r.ok ? r.json() : Promise.reject()).then(d => setComments(d.comments)).catch(() => undefined); }, [id]);
  if (!post) return <div style={{ minHeight: '100vh', padding: '9rem 1.5rem', textAlign: 'center', color: 'var(--white-dim)' }}>Loading post…</div>;
  return <div style={{ minHeight: '100vh', maxWidth: '52rem', margin: '0 auto', padding: '9rem 1.5rem 7rem' }}><Link href="/posts" style={{ color: 'var(--gold)' }}>← Back to posts</Link><article style={{ marginTop: '2rem', borderTop: '1px solid var(--border)', padding: '2rem 0' }}><div style={{ color: 'var(--gold)', fontSize: '.7rem' }}>{post.name} · {post.role} · {post.time}</div><p className="font-display" style={{ whiteSpace: 'pre-line', color: 'var(--white)', fontSize: 'clamp(2rem,4vw,3rem)', marginTop: '1rem' }}>{post.text}</p>{post.image && <img src={post.image} alt="Post media" style={{ width: '100%', marginTop: '2rem' }} />}{post.video && <video controls style={{ width: '100%', marginTop: '2rem' }} src={post.video} />}</article><section><h2 className="font-display" style={{ color: 'var(--white)' }}>Conversation</h2>{comments.map((item, index) => <p key={index} style={{ color: 'var(--text)' }}>{item}</p>)}<form onSubmit={async event => { event.preventDefault(); if (!comment.trim()) return; const response = await fetch(apiUrl(`/api/posts/${id}/comments`), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text: comment }) }); if (response.ok) { setComments([...comments, comment]); setComment(''); } }}><input value={comment} onChange={event => setComment(event.target.value)} placeholder="Add a comment" style={{ width: '70%', padding: '.8rem' }} /><button className="btn-primary"><span>Send</span></button></form></section></div>;
}
